"""Backward-compatible facade — re-exports from backend."""

from neusim.npusim.backend.dvfs_power_getter import (  # noqa: F401
    VfPoint,
    VBWPoint,
    PowerEfficiencyPoint,
    Row,
    Groups,
    SA_POINTS,
    VU_POINTS,
    SRAM_POINTS,
    HBM_POINTS,
    HBM_MC_POINTS,
    HBM_PHY_POINTS,
    HBM_DIE_POINTS,
    HBM_IO_POINTS,
    ICI_POINTS,
    ICI_MC_POINTS,
    ICI_PHY_POINTS,
    AGGREGATE_POWER_COMPONENTS,
    DVFS_VOLTAGE_REGULATOR_OVERHEAD_TABLE,
    FIXED_VOLTAGE_REGULATOR_OVERHEAD_TABLE,
    get_power_from_dvfs,
    get_all_dvfs_configs_for_component,
    get_all_dvfs_configs_for_op,
)
